cookbook_project/cookbook/urls.py
from django.conf.urls import url
from cookbook import views

app_name = 'cookbook'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    url(r'^sign-up/$', views.signup, name='signup'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^myprofile/$', views.myprofile, name='myprofile'),
    url(r'^myprofile/account-settings/$', views.account_settings, name='account_settings'),
    url(r'^myprofile/account-settings/delete-account/$', views.delete_account, name='delete_account'),
    url(r'^myprofile/account-settings/change-password/$', views.change_password, name='change_password'),
    url(r'^myprofile/saved-recipes/$', views.savedrecipes, name='saved-recipes'),
    url(r'^myprofile/upload-recipe/$', views.uploadrecipe, name='upload-recipe'),
    url(r'^user/(?P<user>[\w\-]+)/$', views.view_user, name='view_user'),
    url(r'^user/(?P<user>[\w\-]+)/(?P<recipe_slug>[\w\-]+)/$', views.view_recipe, name='view_recipe'),
    url(r'^user/(?P<user>[\w\-]+)/(?P<recipe_slug>[\w\-]+)/edit/$', views.editrecipe, name='editrecipe'),    
    url(r'^best-rated/$', views.bestrated, name='best-rated'),
    url(r'^newest-recipes/$', views.newestrecipes, name='newest-recipes'),
    url(r'^search/$', views.search, name='search'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^categories/(?P<category_name>[\w\-]+)/', views.view_category, name='view_category'),
    url(r'^help/$', views.about, name='help'),
    url(r'^help/faq/$', views.faq, name='faq'),
    url(r'^help/conversion-charts/$', views.conversioncharts, name='conversion-charts'),
    url(r'^help/recipe-writing-guidelines/$', views.recipeguide, name='recipe-writing-guidelines'),
    url(r'^help/commenting-rules/$', views.commentingrules, name='commenting-rules'),    

    # Ajax urls
    url(r'^save_recipe/$', views.save_recipe, name='save_recipe'),
    url(r'^delete_comment/$', views.delete_comment, name='delete_comment'),
    url(r'^delete_recipe/$', views.delete_recipe, name='delete_recipe'),
    url(r'^rate_recipe/$', views.rate_recipe, name='rate_recipe'),
    url(r'^username_check/$', views.username_check, name='username_check'),
]

cookbook_project/cookbook_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cookbook import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^cookbook/', include('cookbook.urls')),
    url(r'^', include('cookbook.urls')),
    url(r'^admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cookbook_project/cookbook/views.py
# DJANGO IMPORTS
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import IntegrityError
# COOKBOOK IMPORTS
from cookbook.models import Category, Recipe, Comment, Rating
from cookbook.forms import UserForm, RecipeForm, CommentForm, DeleteUserForm, ChangePasswordForm
from django.forms.models import model_to_dict
# DATETIME IMPORTS
from datetime import datetime, timedelta
from itertools import chain


#-HELPER-FUNCTIONS------------------------------------------------------

def username_check(request):
    username = None
    available = None
    if request.method == 'GET':
        username = request.GET['username']

        if username:
            users = User.objects.filter(username__iexact=username)
            available = len(users) == 0

    return HttpResponse(available)
    

@login_required
def rate_recipe(request):
    recipe_id = None
    value = None
    rating  = None
    if request.method == 'GET':
        recipe_id = request.GET['recipe_id']
        recipe = Recipe.objects.get(id=recipe_id)
        value = request.GET['value']

        if recipe and value:
            recipe.rate(request.user, int(value))
            rating = recipe.total_rating

    return HttpResponse(rating)


@login_required
def delete_recipe(request):
    recipe_id = None
    deleted = False
    if request.method == 'GET':
        recipe_id = request.GET['recipe_id']
        recipe = Recipe.objects.get(id=recipe_id)

        if recipe and recipe.user == request.user:
            recipe.delete()
            deleted = True

    return HttpResponse(deleted)
            

@login_required
def delete_comment(request):
    comment_id = None
    deleted = False
    if request.method == 'GET':
        comment_id = request.GET['comment_id']
        comment = Comment.objects.get(id=comment_id)

        if comment and request.user == comment.user:
            comment.delete()
            deleted = True

    return HttpResponse(deleted)
            

@login_required
def save_recipe(request):
    recipe_user = None
    recipe_slug = None
    saved = None
    
    if request.method == 'GET':
        # get the recipe author and recipe slug
        recipe_user = User.objects.get(username=request.GET['user'])
        recipe_slug = request.GET['slug']
            
        # if request contains both
        if recipe_user and recipe_slug:
            # try and get a recipe object
            recipe = Recipe.objects.get(user=recipe_user, slug=recipe_slug)

            # if the recipe object exists
            if recipe:
                # either save or unsave the recipe and set saved to new value
                if recipe not in Recipe.objects.filter(saved_by=request.user):
                    recipe.user_save(request.user)
                    saved = True
                else:
                    recipe.user_unsave(request.user)
                    saved = False
    return HttpResponse(saved)        


#-HOME-SECTION----------------------------------------------------------

def home(request):
    context_dict = {}
    best_rated = Recipe.objects.filter(weighted_rating__gt=0).filter(upload_date__gte=datetime.now()-timedelta(days=7)).order_by('-weighted_rating')[:5]
    new_recipes = Recipe.objects.order_by('-upload_date')[:5]
    context_dict['best_rated'] = best_rated
    context_dict['new_recipes'] = new_recipes
    
    response = render(request, 'cookbook/home.html', context_dict)
    return response

#-USER-SECTION----------------------------------------------------------

def signup(request):
    registered = False

    if request.method == 'POST':
        # check if form is valid
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            # create user
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True

        else:
            # invalid form/errors, print to terminal
            print(user_form.errors)

    else:
        # create blank form
        user_form = UserForm()

    context_dict = {}
    context_dict['user_form'] = user_form
    context_dict['registered'] = registered
    
    return render(request, 'cookbook/signup.html', context_dict)

def user_login(request):
    context_dict = {}

    if request.method == 'POST':
        # check if username and password are valid
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            # check account is not disabled
            if user.is_active:
                # login the user and redirect to their profile
                login(request, user)
                return HttpResponseRedirect(reverse('cookbook:myprofile'))

            # inactive account
            else:
                context_dict['errors'] = ['Your CookBook account is disabled.']
                return render(request, 'cookbook/user_login.html', context_dict)

        # invalid login details
        else:
            print('Invalid login details: {0}, {1}'.format(username, password))
            context_dict['errors'] = ['Invalid login details']
            return render(request, 'cookbook/user_login.html', context_dict)
        
    else:
        # Not HTTP POST
        return render(request, 'cookbook/user_login.html', context_dict)

@login_required
def user_logout(request):
    # logout user and redirect to home page
    logout(request)
    return HttpResponseRedirect(reverse('cookbook:home'))

@login_required
def myprofile(request):
    context_dict = {}
        
    recipes = Recipe.objects.filter(user=request.user).order_by('-upload_date')
    recent_comments = Comment.objects.filter(recipe__in=recipes).order_by('-upload_date')[:10]
    
    context_dict['recent_comments'] = recent_comments
    context_dict['recipes'] = recipes

    return render(request, 'cookbook/myprofile.html', context_dict)

@login_required
def account_settings(request):
    return render(request, 'cookbook/account_settings.html')

def delete_account(request):
    context_dict = {}
    deleted = False
    
    if request.method == 'POST':
        confirm = request.POST.get('confirm')
        if confirm:
            try:
                request.user.delete()
            except:
                pass
            deleted = True

    context_dict['deleted'] = deleted
    context_dict['form'] = DeleteUserForm()
    
    return render(request, 'cookbook/delete_account.html', context_dict)

@login_required
def change_password(request):
    context_dict = {}

    changed = False
    if request.method == 'POST':
        # check if form is valid
        form = ChangePasswordForm(data=request.POST, user=request.user)

        if form.is_valid() and authenticate(username=request.user.username, password=form.cleaned_data['old']):
            request.user.set_password(form.cleaned_data['new'])
            request.user.save()
            changed = True

        else:
            print(form.errors)

    else:
        # create blank form
        form = ChangePasswordForm(user=request.user)

    context_dict['form'] = form
    context_dict['changed'] = changed
    
    return render(request, 'cookbook/change_password.html', context_dict)


@login_required
def savedrecipes(request):
    context_dict = {}
	
    saved_recipes = Recipe.objects.filter(saved_by=request.user)[::-1]
	
    recipes = Recipe.objects.filter(user=request.user)
    recent_comments = Comment.objects.filter(recipe__in=recipes)
    if recent_comments:
        recent_comments = recent_comments.order_by('-upload_date')[:10]

    context_dict['recent_comments'] = recent_comments
    context_dict['saved_recipes'] = saved_recipes
    
    return render(request, 'cookbook/saved_recipes.html', context_dict)

@login_required
def uploadrecipe(request):
    context_dict = {}
    recipe_form = RecipeForm()
    if request.method == 'POST':
        # check if form is valid
        recipe_form = RecipeForm(request.POST, request.FILES)
        
        if recipe_form.is_valid():
            # create
            recipe = recipe_form.save(commit=False)
            recipe.user = request.user
            if 'picture' in request.FILES:
                recipe.picture = request.FILES['picture']
            recipe.save()
            return HttpResponseRedirect(reverse('cookbook:view_recipe', args=[recipe.user, recipe.slug]))

    context_dict['recipe_form'] = recipe_form
    return render(request, 'cookbook/uploadrecipe.html', context_dict)


@login_required
def editrecipe(request, user, recipe_slug):
    context_dict = {}
    recipe = None
    form = None
    errors = []

    try:
        recipe = Recipe.objects.get(user=User.objects.get(username=user), slug=recipe_slug)
        if request.user != recipe.user:
            raise Exception

        # Submitting changes
        if request.method == 'POST':
            form = RecipeForm(request.POST, request.FILES, instance=recipe)
            if form.is_valid():
                recipe = form.save(commit=False)
                recipe.user = request.user
                recipe.last_modified = timezone.now()
                if 'picture' in request.FILES:
                    recipe.picture = request.FILES['picture']
                recipe.save()
                return HttpResponseRedirect(reverse('cookbook:view_recipe', args=[recipe.user, recipe.slug]))                
            
        # Start editing
        else:
            form = RecipeForm(initial=model_to_dict(recipe))

    except (Recipe.DoesNotExist):      
        recipe = None
        form = None

    except (IntegrityError):

cookbook_project/templates/cookbook/account_settings.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
	- Account Settings
{% endblock %}

{% block body_block %}
	<h2>Manage Your Account</h2>
	<ul>
		<li><a href="{% url 'cookbook:change_password' %}">Change your password</a></li>
		<li><a href="{% url 'cookbook:delete_account' %}">Delete your account</a></li>
		
	</ul>
{% endblock %}

cookbook_project/templates/cookbook/categories.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Categories
{% endblock %}
{% block body_block %}
	<h2>Categories</h2>
	<div class="category_list">
	{% if categories %}
		{% for category in categories %}
		<div class="category_detail" >
			<a href="{% url 'cookbook:view_category' category.name %}">
			
			<div class="category_name">
			<big>{{ category.name }}</big></br>
			</div>
			
			<img class="category_list_image" src="{{ MEDIA_URL }}{{ category.picture }}" height="200" width="200">
			
			</a>
		</div>
		{% endfor %}
	{% else %}
		There are no categories!
	{% endif %}
	</div>

{% endblock %}

cookbook_project/templates/cookbook/commenting-rules.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Commenting rules
{% endblock %}
{% block body_block %}
	<h2>Commenting rules on CookBook</h2>
<p style="font-size:20px">The general rule for commenting is: be nice.
Remember that if you break the rules, your comments may be deleted, and your account deleted as well if we judge it necessary.
Here are the guidelines for commenting. <p> 
<ul>
<li>Do not post racist, sexist, homophobic, or otherwise bigoted comments.</li>
<li>Do not post threats or encourage self-harm.</li>
<li>Do not post or link to anything pornographic, or illegal (including illegal file sharing).</li>
<li>Do not spam: no excessive posting, repeated self-promotion, or paid referral links.</li>
<li>Do not insult other users.</li>
<li>If you want to criticise a recipe or suggest changes, be constructive: explain why you think that the recipe is imperfect and give your suggestions.</li>
</ul>
{% endblock %}

cookbook_project/templates/cookbook/commeting-rules.html
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Commenting rules
{% endblock %}
{% block body_block %}
	<h1>Commenting rules on CookBook</h1>
<p style="font-size:20px">The general rule for commenting is: be nice.
Remember that if you break the rules, your comments may be deleted, and your account deleted as well if we judge it necessary.
Here are the guidelines for commenting. <p> 
<ul>
<li>Do not post racist, sexist, homophobic, or otherwise bigoted comments.</li>
<li>Do not post threats or encourage self-harm.</li>
<li>Do not post or link to anything pornographic, or illegal (including illegal file sharing).</li>
<li>Do not spam: no excessive posting, repeated self-promotion, or paid referral links.</li>
<li>Do not insult other users.</li>
<li>If you want to criticise a recipe or suggest changes, be constructive: explain why you think that the recipe is imperfect and give your suggestions.</li>
</ul>
{% endblock %}

cookbook_project/templates/cookbook/editrecipe.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% if recipe %}
- edit {{ recipe.name }}
{% else %}
- Oops
{% endif %}
{% endblock %}

{% block body_block %}
	{% if recipe %}
		<h2>Edit {{ recipe.name }}</h2>
		<div id="recipe_form_holder">
			<form enctype="multipart/form-data" id="recipe_form" method="post" action="{% url 'cookbook:editrecipe' recipe.user recipe.slug %}">
				{% csrf_token %}
				<ul>
				{% for error in errors %}
					<li>{{ error }}</li>
				{% endfor %}
				</ul>
				{{ form.errors }}
				{{ recipe_form.as_p }}
				<div class="button_wrapper">
					<input type="submit" value="Save changes" />
					<input type="button" id="discard_changes" value="Cancel" />
				</div>
			</form>
		</div>
	{% else %}
		<h2>Oops!</h2>
		<p>Oh no it appears that recipe doesn't exist or is not your recipe. If this is your recipe make sure you are logged in before editing!</p>
	{% endif %}
{% endblock %}

cookbook_project/templates/cookbook/faq.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- FAQ
{% endblock %}
{% block body_block %}
	<h2>Frequently Asked Questions</h2>
	<p style="font-size:26px">How do I write a recipe?</p>
	You can find guidelines for writing recipes <a href="{% url 'cookbook:recipe-writing-guidelines' %}">here</a>.
	<p style="font-size:26px">There is a bug on the website, what do I do?</p>
	If you find a bug on our website, please contact Peter Maitland at <a href>2200049m@student.gla.ac.uk</a>, explaining the bug, what you were doing when it happened,
	and a screenshot if possible. We will keep you up to date on how we are dealing with the bug.
	<p style="font-size:26px">I want to report a user, who can I contact?</p>
	You should only report users that have broken the <a href="{% url 'cookbook:commenting-rules' %}">commenting rules</a>.
	If you want to report a user, you can write an email to Hope Doolan at <a href>2182667d@student.gla.ac.uk</a>, state your username, 
	the username of the person you want to report and why you want to report them with links to pages where you think the user may have broken some rules. 
	<p style="font-size:26px">I have a suggestion for the website, who can I contact to pitch my idea?</p>
	If you have an idea that you want for improving CookBook that you want to share with us, contact Iain Cattermole at <a href>2189570c@student.gla.ac.uk</a>.
	We may use your idea and make the site even better!
	<p style="font-size:26px">I would like to work with/for CookBook, who can I contact?</p>
	If you want to work for us or in partnership with us, please contact Lukas Backis at <a href>2145673B@student.gla.ac.uk</a>.

{% endblock %}

cookbook_project/templates/cookbook/home.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Home
{% endblock %}
{% block body_block %}
	<p id="welcome">
	<h2>Welcome to Cookbook</h2>
	
	{% if user.is_authenticated %}
		<div id="home_upload">
		<form method="GET" action="{% url 'cookbook:upload-recipe' %}">
			<input type="submit" value="Add your own recipe">
		</form>
		</div>
	{% endif %}
	
	Vegetarian <img class="dietary_image_key" src="{% static 'cookbook/images/vegetarian.png' %}" height="30" width="30"> 
	| Vegan <img class="dietary_image_key" src="{% static 'cookbook/images/vegan.png' %}" height="30" width="30">
	| Dairy-free <img class="dietary_image_key" src="{% static 'cookbook/images/dairy-free.png' %}" height="30" width="30">
	| Gluten-free <img class="dietary_image_key" src="{% static 'cookbook/images/gluten-free.png' %}" height="30" width="30">
	
	<div class="recipe_spicy">
		| Mild <img class="spicy" src="{% static 'cookbook/images/spicy.png' %}" height="14" width="15">
	</div>
	
	<div class="recipe_spicy">
		| Hot 
		{% with ''|center:2 as range %}
		{% for _ in range %}
			<img class="spicy" src="{% static 'cookbook/images/spicy.png' %}" height="14" width="15">			
		{% endfor %}
		{% endwith %}
	</div>
	
	<div class="recipe_spicy">
		| Super spicy 
		{% with ''|center:3 as range %}
		{% for _ in range %}
			<img class="spicy" src="{% static 'cookbook/images/spicy.png' %}" height="14" width="15">			
		{% endfor %}
		{% endwith %}
	</div>
	
	</p>	
	<div class="recipe_list">
		<h2><a class="no_u" href="{% url 'cookbook:newest-recipes' %}">Newest Recipes</a></h2>
		
		{% if new_recipes %}
			{% for recipe in new_recipes %}
				{% include 'cookbook/include/recipe_detail.html' %}
			{% endfor %}
		{% else %}
			The newest recipes will appear here!
		{% endif %}
	</div>
	
	<div class="recipe_list">
		<h2><a class="no_u" href="{% url 'cookbook:best-rated' %}">Best Rated This Week</a></h2>
		{% if best_rated %}
			{% for recipe in best_rated %}
				{% include 'cookbook/include/recipe_detail.html' %}
			{% endfor %}
		{% else %}
			The best rated recipes will appear here!
		{% endif %}
	</div>
	
{% endblock %}

cookbook_project/templates/cookbook/myprofile.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- {{ user.username }}
{% endblock %}
{% block body_block %}
	<h2>My Profile - {{ user.username }}</h2>
	
	<div id="settings_link">
		<form method="GET" action="{% url 'cookbook:account_settings' %}">
			<input type="submit" value="Manage your account">
		</form>
	</div>
	
	<div class="recipe_options">
		<h2>
			<a class="active" href="{% url 'cookbook:saved-recipes' %}">Saved Recipes</a> | 
			<a class="active" href="{% url 'cookbook:upload-recipe' %}">Upload Recipe</a>
		</h2>
	</div>
	
	<div id="recent_comments">
	<h2>Recent comments</h2>
	{% if recent_comments %}
		{% for comment in recent_comments %}
				<div class="comment_box">
				<p class="comment_user">
				<a href="{% url 'cookbook:view_user' comment.user.username %}">{{ comment.user }}</a>
				on {{ comment.upload_date }} about
				<a href="{% url 'cookbook:view_recipe' comment.recipe.user comment.recipe.slug %}">{{ comment.recipe.name }}</a>
				</p>
				<p class="comment_text">
				{{ comment.text }}
				</p>
				</div>
		{% endfor %}
	{% else %}
		No comments yet!
	{% endif %}
	</div>
	
	<div class="recipe_list" id="my_recipe_list">
	<h2>
	My Recipes
	</h2>
	{% if recipes %}
		<div class="recipe_list">
		{% for recipe in recipes %}
			<div class="recipe_detail" id="{{ recipe.id }}">
				
				<div class="recipe_name">
					<a href="{% url 'cookbook:view_recipe' recipe.user.username recipe.slug %}">
					{% if recipe.picture %}
					<img class="list_image" src="{{ MEDIA_URL }}{{ recipe.picture }}" height="125" width="125">
					{% else %}
					<img class="list_image" src="{% static 'cookbook/images/default.png' %}" height="125" width="125">
					{% endif %}
				<big>{{ recipe.name }}</big></a>
				</div>
				
				<div class="recipe_date">
					uploaded: {{ recipe.upload_date }}<br>
					{% if recipe.last_modified %}
						last modified: {{ recipe.last_modified }}
					{% endif %}
				</div>
					
				<div class="recipe_desc">
					<i>"{{ recipe.description }}"</i>
				</div>
				
				<div class="recipe_info">
					
					Views: {{ recipe.views }} - Comments: {{ recipe.no_of_comments }}<br>
					
					{{ recipe.category }} 
					| Serves: {{ recipe.serves }} 
					| Cooking time: {{ recipe.cooking_time }} minutes 
					
					<div class="recipe_rating">
					| <span class="stars">{{ recipe.total_rating }}</span> ({{ recipe.no_of_ratings }})
					</div>

					{% if recipe.spice > 0 %}
					<div class="recipe_spicy">
					|
					{% with ''|center:recipe.spice as range %}
					{% for _ in range %}
						<img class="spicy" src="{% static 'cookbook/images/spicy.png' %}" height="14" width="15">			
					{% endfor %}
					{% endwith %}
					</div>
					{% endif %}
	
				</div>
				
				<div class="dietary_info">
					{% if recipe.is_gluten_free %}
					<img class="dietary_image" src="{% static 'cookbook/images/gluten-free.png' %}" height="30" width="30">
					{% endif %}
					{% if recipe.is_vegan %}
					<img class="dietary_image" src="{% static 'cookbook/images/vegan.png' %}" height="30" width="30">
					{% else %}
						{% if recipe.is_vegetarian %}
						<img class="dietary_image" src="{% static 'cookbook/images/vegetarian.png' %}" height="30" width="30">
						{% endif %}
						{% if recipe.is_dairy_free %}
						<img class="dietary_image" src="{% static 'cookbook/images/dairy-free.png' %}" height="30" width="30">
						{% endif %}
					{% endif %}
				</div>
				
				<button id="{{ recipe.id }}" data-name="{{ recipe.name }}" title="Delete" class="delete_recipe_button" >&#10006 </button>
			
			</div>
		{% endfor %}
		</div>
	{% else %}
		You haven't posted any recipes yet, why not start now?
	{% endif %}
	</div>


{% endblock %}

cookbook_project/templates/cookbook/saved_recipes.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Saved Recipes
{% endblock %}
{% block body_block %}
	<h2>Saved Recipes</h2>
	{% if saved_recipes %}
		{% for recipe in saved_recipes %}
			{% include 'cookbook/include/recipe_detail.html' %}
		{% endfor %}
	{% else %}
		Save your favourite recipes and they will appear here!
	{% endif %}
{% endblock %}

cookbook_project/templates/cookbook/signup.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Sign Up
{% endblock %}
{% block body_block %}
<h2>Register to CookBook</h2>
	{% if registered %}
		Thank you for registering! You can login and start posting recipes <a href="{% url 'cookbook:user_login' %}">here</a>.
	{% else %}
		<div id="signup">
			<form id="user_form" method="post" action="{% url 'cookbook:signup' %}" enctype="multipart/form-data">
				{% csrf_token %}
				<!-- Display each form -->
				<p>{{ user_form.username.errors }}</p>
				<div><label class="form_label">Username: </label><p id="username_check"></p>{{ user_form.username }}</div>
				<p>{{ user_form.email.errors }}</p>
				<p><label class="form_label">Email: </label>{{ user_form.email }}</p>
				<p>{{ user_form.password.errors }}</p>
				<p><label class="form_label">Password: </label>{{ user_form.password }}</p>
				<p>{{ user_form.reenter_password.errors }}</p>
				<p><label class="form_label">Re-enter password: </label>{{ user_form.reenter_password }}</p>
				<!-- Provide a button to click to submit the form. -->
				<div class="button_wrapper">
					<input id="register_button" type="submit" name="submit" value="Register"/>
				</div>
			</form>
			<p id="no_account">Already have an account? Login <a href="{% url 'cookbook:user_login' %}">here!</a>
		</div>
	{% endif %}
{% endblock %}

cookbook_project/templates/cookbook/uploadrecipe.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Upload a Recipe
{% endblock %}

{% block body_block %}
	<h2>Upload a New Recipe</h2>
	<div id="recipe_form_holder">
		<form enctype="multipart/form-data" id="recipe_form" method="post" action="{% url 'cookbook:upload-recipe' %}">
			{% csrf_token %}
			{{ recipe_form.as_p }}
			<div class="button_wrapper">
				<input type="submit" value="Upload" />
			</div>
		</form>
	</div>
	
{% endblock %}

cookbook_project/templates/cookbook/user_login.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}
{% block title_block %}
- Login
{% endblock %}
{% block body_block %}
  	<h2>Login to CookBook</h2>
	<div id="login">
		<form id="login_form" method="post" action="{% url 'cookbook:user_login' %}">
			{% csrf_token %}
			{% if errors %}
				<ul>
				{% for error in errors %}
					<li>{{ error }}</li>
				{% endfor %}
				</ul>
			{% endif %}
			<p><label class="form_label" >Username: </label><input type="text" name="username" value="" /></p>
			<p><label class="form_label" >Password: </label><input type="password" name="password" value="" /></p>
			<div class="button_wrapper">
				<input type="submit" value="Sign in" />
			</div>
		</form>
		<p id="no_account">Don't have an account? Sign up <a href="{% url 'cookbook:signup' %}">here!</a>
	</div>
{% endblock %}

cookbook_project/templates/cookbook/view_user.html
<!DOCTYPE html>
{% extends 'cookbook/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% if author %}
- {{ author }}
{% else %}
- Oops
{% endif %}
{% endblock %}

{% block body_block %}
	{% if author %}
		<h2>{{ author }}</h2>
		
		<div id="author_details">
		
		</div>
	
		<h2>{{ author }}'s Recipes</h2>
		
		<div class="recipe_list">
		{% if recipes %}
			{% for recipe in recipes %}
				{% include 'cookbook/include/recipe_detail.html' %}
			{% endfor %}
		{% else %}
			This user has not uploaded any recipes.
		{% endif %}
		</div>
	{% else %}
		This user does not exist!
	{% endif %}
{% endblock %}